# render.yaml
services:
  - type: web
    name: digital-street
    env: node
    plan: free
    buildCommand: npm install && npm run install-backend
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
